<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Kafdeck.Infrastructure.Kafka</AssemblyName>
    <RootNamespace>Kafdeck.Infrastructure.Kafka</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Kafdeck.Core/Kafdeck.Core.csproj" />
    <ProjectReference Include="../Kafdeck.Infrastructure.Configuration/Kafdeck.Infrastructure.Configuration.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Kafdeck.Architecture.Tests" />
  </ItemGroup>
</Project>
