<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Kafdeck.Infrastructure.Kafka</AssemblyName>
    <RootNamespace>Kafdeck.Infrastructure.Kafka</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Kafdeck.Core/Kafdeck.Core.csproj" />
  </ItemGroup>
</Project>
