<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Kafdeck.Architecture.Tests</AssemblyName>
    <RootNamespace>Kafdeck.Architecture.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/backend/Kafdeck.Api/Kafdeck.Api.csproj" />
    <ProjectReference Include="../../src/backend/Kafdeck.Core/Kafdeck.Core.csproj" />
    <ProjectReference Include="../../src/backend/Modules/Kafdeck.Modules.Clusters/Kafdeck.Modules.Clusters.csproj" />
    <ProjectReference Include="../../src/backend/Modules/Kafdeck.Modules.Topics/Kafdeck.Modules.Topics.csproj" />
    <ProjectReference Include="../../src/backend/Modules/Kafdeck.Modules.Records/Kafdeck.Modules.Records.csproj" />
    <ProjectReference Include="../../src/backend/Modules/Kafdeck.Modules.Consumers/Kafdeck.Modules.Consumers.csproj" />
    <ProjectReference Include="../../src/backend/Modules/Kafdeck.Modules.Schemas/Kafdeck.Modules.Schemas.csproj" />
    <ProjectReference Include="../../src/backend/Modules/Kafdeck.Modules.Administration/Kafdeck.Modules.Administration.csproj" />
    <ProjectReference Include="../../src/backend/Infrastructure/Kafdeck.Infrastructure.Configuration/Kafdeck.Infrastructure.Configuration.csproj" />
    <ProjectReference Include="../../src/backend/Infrastructure/Kafdeck.Infrastructure.Kafka/Kafdeck.Infrastructure.Kafka.csproj" />
    <ProjectReference Include="../../src/backend/Infrastructure/Kafdeck.Infrastructure.Ecosystem/Kafdeck.Infrastructure.Ecosystem.csproj" />
    <ProjectReference Include="../../src/backend/Infrastructure/Kafdeck.Infrastructure.SchemaRegistry/Kafdeck.Infrastructure.SchemaRegistry.csproj" />
    <ProjectReference Include="../../src/backend/Infrastructure/Kafdeck.Infrastructure.Security/Kafdeck.Infrastructure.Security.csproj" />
    <ProjectReference Include="../../src/backend/Infrastructure/Kafdeck.Infrastructure.Persistence/Kafdeck.Infrastructure.Persistence.csproj" />
  </ItemGroup>
</Project>
