name: container

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'deploy/docker/**'
  push:
    branches: [main]
    tags:
      - 'v*'
    paths:
      - 'Dockerfile'
      - 'deploy/docker/**'

permissions:
  contents: read

jobs:
  build:
    name: container-build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build OCI image
        run: docker build --pull --tag kafdeck:ci .
